// portal/apps/dashboard/src/app/components/card/card.component.ts
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';

@Component({
  selector: 'dashboard-card',
  standalone: true,
  imports: [],
  templateUrl: './card.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardComponent {
  @Input() name = '';
  @Input() description = '';
  @Input() url = '';
  @Input() tags: string[] = [];

}

<div class="w-full h-full bg-white py-4 px-6 flex flex-col justify-start
            shadow-lg rounded-lg cursor-pointer
            sm:hover:scale-110"
>
  <div class="flex flex-row justify-between">
    <!--    <img class="w-8 h-8 rounded-full mr-4 border-2 border-neutral-300" src="https://flowbite.com/docs/images/people/profile-picture-1.jpg" alt="Jese Leos">-->
    <label class="text-neutral-800 text-2xl font-semibold">{{name}}</label>

    <a class="py-2 px-3 text-xs font-medium text-center text-white bg-primary-700 rounded-full cursor-pointer
              hover:bg-primary-800 focus:outline-none"
       href="{{url}}"
       target="_blank">
      Go
    </a>

  </div>
  <p class="my-2 text-neutral-300 line-clamp-3">{{description}}</p>

  <div class="flex justify-end mt-auto ">
    <a href="#"
       class="bg-accent-100 text-accent-700 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded">
      Frontend
    </a>
    <a href="#"
       class="bg-accent-100 text-accent-700 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded">
      Angular
    </a>
    <!--      <a href="#" class="text-xl font-medium text-indigo-500">John Doe</a>-->
  </div>
</div>

// browser-extension/components/card/Card.tsx
import type {ComponentProps} from "react";
import type {GoLink} from "~entities/search-response";

interface CardProps extends ComponentProps<any> {
    item: GoLink
}

export const Card = ({item}: CardProps) => {
    return (
        <div className="w-full h-full bg-white py-4 px-6 flex flex-col justify-start
            rounded-lg shadow-md shadow-neutral-200 dark:shadow-dark-500 dark:bg-dark-700">

            <div className="flex flex-row justify-between">
                <label
                    className="text-2xl text-primary-900 font-semibold dark:text-primary-400 uppercase">{item.name}</label>

                <a href={item.redirectUrl} target="_blank"
                   className="bg-primary-900 hover:bg-primary-800 py-2 px-2.5 focus:outline-none rounded-full inline-flex">
                    <i className="fa fa-rocket text-xs leading-lg text-white pr-px pt-px"></i>
                </a>
            </div>

            <p className="my-2 text-neutral-500 line-clamp-3 dark:text-dark-200">{item.description}</p>

            <div className="flex flex-wrap justify-end mt-auto overflow-hidden">
                {
                    item.tags.map((tag) =>
                        <span key={tag}
                              className="bg-accent-100 text-accent-700 text-xs font-semibold mt-1 mr-2 px-2.5 py-0.5 rounded">{tag}</span>
                    )
                }
            </div>
        </div>
    )
}
