// browser-extension/components/navbar/Navbar.tsx
import React from "react";

export const Navbar = () => {
    return (
        <nav className="top-0 bg-primary-900 z-50 w-full px-2 py-3 navbar-expand-lg shadow">
            <div className="container px-4 mx-auto flex items-center justify-between">
                <a
                    className="text-neutral-50 text-xl font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase">
                    Go Links Engine
                </a>
                <div className="flex">
                    <a className="text-neutral-50 text-xs uppercase font-bold mr-4"
                       href="https://github.com/darge98/Go-Links"
                       target="_blank" rel="noopener noreferrer">
                        <i className="fab fa-github text-lg leading-lg"></i>
                    </a>
                </div>
            </div>
        </nav>

    )
}

// portal/apps/dashboard/src/app/components/navbar/navbar.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {ThemeToggleComponent} from "../theme-toggle/theme-toggle.component";

@Component({
    selector: 'dashboard-navbar',
    standalone: true,
    templateUrl: './navbar.component.html',
    imports: [
        ThemeToggleComponent
    ],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class NavbarComponent {
}

<nav
  class="top-0 bg-primary-700 z-50 w-full flex flex-wrap items-center justify-between px-2 py-3 navbar-expand-lg bg-white shadow bg-neutral-50">
  <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
    <a class="text-neutral-50 text-xl font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase">
      Go Links Search Engine
    </a>
    <div class="flex">
      <dashboard-theme-toggle class="flex justify-center"></dashboard-theme-toggle>
      <a class="text-neutral-50 text-xs uppercase font-bold ml-4"
         href="https://github.com/darge98/Go-Links"
         target="_blank" rel="noopener noreferrer">
        <i class="fab fa-github text-lg leading-lg"></i>
      </a>
    </div>
  </div>
</nav>
