// portal/libs/components/src/lib/search-bar/search-bar.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Output,
  ViewChild
} from '@angular/core';
import {FormsModule} from "@angular/forms";

@Component({
  selector: 'portal-search-bar',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './search-bar.component.html',
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SearchBarComponent {

  @Output() whenValueChange = new EventEmitter<string>();
  @ViewChild('searchBarInput') searchBarInput: ElementRef | undefined;

  @HostListener('document:keydown.control.k', ['$event']) onCtrlK(event: KeyboardEvent) {
    event.preventDefault();
    this.searchBarInput?.nativeElement.focus();
  }

  valueChange(value: string): void {
    this.whenValueChange.emit(value);
  }
}

<div class="relative">
  <form class="flex flex-row flex-wrap items-center">

    <!-- bg-white -->
    <div
      class="relative flex flex-wrap justify-between items-baseline w-full max-w-xl mx-auto rounded-full h-18 lg:w-1/2">
      <span
        class="z-10 h-full leading-snug font-normal absolute text-center text-neutral-300 bg-transparent rounded text-base items-center justify-center w-8 pl-3 py-3">
          <i class="fas fa-search"></i>
      </span>
      <input type="text"
             #searchBarInput
             ngModel
             [ngModelOptions]="{standalone: true}"
             (ngModelChange)="valueChange(searchBarInput.value)"
             placeholder="e.g Java"
             class="text-sm w-full pl-10 pr-16
             drop-shadow-lg border-2 px-3 py-3 outline-none rounded-full placeholder-neutral-300 text-neutral-800
             focus:border-1 focus:border-accent-400 focus:ring-0 focus:ring-accent-400 focus:outline-none
             hover:ring-dark-300
             dark:bg-dark-800 dark:hover:bg-dark-700"/>
      <span
        class="z-10 h-full leading-snug absolute text-neutral-300 bg-transparent rounded text-base py-3 mr-4 flex-none text-xs font-semibold right-0">
          Ctrl K
      </span>
    </div>
  </form>
</div>

// browser-extension/components/searchbar/SearchBar.tsx
import React, {ComponentProps} from "react";

interface SearchBarProps extends ComponentProps<any> {
    className?: string;
    onChange?: (text: string) => void;
}

export const SearchBar = ({className, onChange}: SearchBarProps) => {
    return (
        <form className={"flex items-center " + className}>
            <div className="relative w-full">
                <div className="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <i className="fas fa-search"/>
                </div>
                <input type="text" id="voice-search"
                       className="text-sm w-full pl-10 pr-16 bg-white
             drop-shadow-lg border-2 px-3 py-3 outline-none rounded-full placeholder-neutral-300 text-neutral-800
             focus:border-1 focus:border-accent-400 focus:ring-0 focus:ring-accent-400 focus:outline-none
             hover:ring-dark-300"
                       onChange={e => onChange(e.target.value)}
                       placeholder="e.g Java, git, Pull Request, ..." />
            </div>
            {/*<button type="submit"*/}
            {/*        className="inline-flex items-center py-2.5 px-3 ml-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">*/}
            {/*    <i className="fas fa-search"/>*/}
            {/*    /!*Search*!/*/}
            {/*</button>*/}
        </form>
    )
}
